const MVAVE_PRODUCTS = "https://www.m-vave.com/products";
const MVAVE_DOWNLOADS = "https://www.m-vave.com/appdownload";

function item(data) {
  const product = Object.assign({
    brand: "M-VAVE",
    instruments: ["guitarra", "baixo", "violao"],
    ir: false,
    software: "Sem editor dedicado",
    officialUrl: MVAVE_PRODUCTS,
    bestFor: "Quem quer uma solução prática e compacta.",
    avoidIf: "Você precisa de recursos que não aparecem nas especificações deste modelo.",
    pros: [],
    cons: [],
    specs: [],
    related: [],
    featured: false
  }, data);
  product.image = product.image || "/assets/img/equipment/" + product.id + ".webp";
  return product;
}

export const STORE_CATEGORIES = [
  ["todos", "Todos"],
  ["multiefeitos", "Pedaleiras"],
  ["ir-loader", "IR loaders"],
  ["midi", "Controladores MIDI"],
  ["page-turner", "Viradores de página"],
  ["pedais", "Pedais e loopers"],
  ["pratica", "Estudo e áudio"],
  ["acessorios", "Acessórios"]
];

export const EQUIPMENT_ITEMS = [
  item({ id: "cube-baby", name: "Cube Baby", category: "multiefeitos", instruments: ["guitarra"], ir: true, software: "CubeSuite", summary: "Pedaleira ultracompacta para guitarra com efeitos, bateria recarregável e carregamento de IR.", bestFor: "Primeiro setup para tocar em fones, gravar e sair em linha gastando pouco.", avoidIf: "Você precisa de muitos footswitches ou edição profunda durante o show.", pros: ["Compacta e recarregável", "Carrega IR de terceiros", "Boa porta de entrada"], cons: ["Poucos controles físicos", "Fluxo depende do editor"], specs: [["Perfil", "Guitarra"], ["IR", "Loader integrado"], ["Editor", "CubeSuite"], ["Uso", "Fone, linha e gravação"]], amazonQuery: "M-VAVE Cube Baby pedaleira guitarra", featured: true, related: ["tank-g", "tank-mini", "ir-box"] }),
  item({ id: "cube-baby-bass", name: "Cube Baby Bass", category: "multiefeitos", instruments: ["baixo"], ir: true, software: "CubeSuite", summary: "Versão da Cube Baby dedicada ao baixo, com efeitos e oito posições de CAB IR.", bestFor: "Baixistas que querem um rig pequeno para fone, gravação e mesa.", avoidIf: "Você precisa de roteamento avançado ou muitos efeitos simultâneos.", pros: ["Foco em baixo", "Oito CAB IR", "Portátil"], cons: ["Controles compactos", "Pouca navegação no pedal"], specs: [["Perfil", "Baixo"], ["IR", "8 CAB IR"], ["Editor", "CubeSuite"], ["Energia", "Bateria recarregável"]], amazonQuery: "M-VAVE Cube Baby Bass pedaleira", featured: true, related: ["tank-b", "annblack-box", "ir-box"] }),
  item({ id: "cube-baby-ac", name: "Cube Baby AC", category: "multiefeitos", instruments: ["violao"], ir: true, software: "CubeSuite", summary: "Processador compacto para violão eletroacústico, pensado para recuperar naturalidade no som em linha.", bestFor: "Violão em igreja, palco pequeno, gravação direta ou estudo com fones.", avoidIf: "Você precisa de entradas de microfone ou mixagem completa de voz e instrumento.", pros: ["Voltada ao violão", "Aceita IR", "Cabe no bag"], cons: ["Interface compacta", "Exige ajuste cuidadoso de ganho"], specs: [["Perfil", "Violão"], ["IR", "Loader integrado"], ["Editor", "CubeSuite"], ["Uso", "Linha e fones"]], amazonQuery: "M-VAVE Cube Baby AC violão", featured: true, related: ["ir-box", "annblack-box", "mk-300"] }),
  item({ id: "tank-g", name: "TANK-G", category: "multiefeitos", instruments: ["guitarra"], ir: true, software: "M-EFCS", summary: "Pedaleira para guitarra com 36 presets, modelos de amplificador, oito CAB IR e controle por aplicativo.", bestFor: "Quem quer mais controle ao vivo que a Cube Baby sem partir para uma pedaleira grande.", avoidIf: "Você quer tela ampla, cadeia muito flexível ou muitas conexões profissionais.", pros: ["36 presets", "Oito CAB IR", "App e editor"], cons: ["Revisões de hardware exigem atenção", "Edição avançada fica no app"], specs: [["Perfil", "Guitarra"], ["Presets", "36"], ["CAB IR", "8"], ["Editor", "M-EFCS"]], amazonQuery: "M-VAVE TANK-G pedaleira", featured: true, related: ["tank-mini", "mk-20", "cube-baby"] }),
  item({ id: "tank-b", name: "TANK-B", category: "multiefeitos", instruments: ["baixo"], ir: true, software: "M-EFCS", summary: "Pedaleira da família TANK dedicada ao baixo, com modelagem, efeitos e controle por aplicativo.", bestFor: "Baixista que quer presets, IR de gabinete e portabilidade em um único pedal.", avoidIf: "Você precisa de cadeia extensa ou muitas saídas independentes.", pros: ["Feita para baixo", "Presets e app", "Formato compacto"], cons: ["Confira a revisão antes do firmware", "Interface física reduzida"], specs: [["Perfil", "Baixo"], ["IR", "CAB IR"], ["Editor", "M-EFCS"], ["Uso", "Palco e estudo"]], amazonQuery: "M-VAVE TANK-B pedaleira baixo", featured: true, related: ["cube-baby-bass", "annblack-box", "mk-300"] }),
  item({ id: "tank-mini", name: "TANK MINI", category: "multiefeitos", instruments: ["guitarra"], ir: true, software: "M-EFCS", summary: "Multiefeitos compacto com conectividade sem fio, aplicativo e importação de recursos pelo editor.", bestFor: "Setup portátil com mais possibilidades que um headphone amp.", avoidIf: "Você prefere todos os ajustes em botões dedicados.", pros: ["Compacto", "App e editor", "Boa mobilidade"], cons: ["Edição depende de tela externa", "Nomes parecidos entre revisões"], specs: [["Perfil", "Guitarra"], ["Editor", "M-EFCS"], ["Conexão", "USB e sem fio"], ["Firmware", "Disponível no portal oficial"]], amazonQuery: "M-VAVE Tank Mini pedaleira", featured: true, related: ["tank-g", "cube-baby", "pocket-amp"] }),
  item({ id: "tank-pro", name: "TANK-PRO", category: "multiefeitos", instruments: ["guitarra", "baixo"], ir: true, software: "M-EFCS / portal oficial", summary: "Modelo avançado com mais de 300 efeitos, 90 modelos de amp, 90 gabinetes, bateria e looper longo.", bestFor: "Quem quer concentrar palco, criação e gravação em uma pedaleira M-VAVE mais completa.", avoidIf: "Portabilidade mínima e preço baixo são prioridades absolutas.", pros: ["Mais de 300 efeitos", "Saídas XLR e estéreo", "Looper e bateria"], cons: ["Maior e mais complexa", "Ecossistema ainda em evolução"], specs: [["Efeitos", "300+"], ["Amps", "90"], ["Gabinetes", "90"], ["Looper", "até 150,8 s"]], amazonQuery: "M-VAVE TANK PRO pedaleira", featured: true, related: ["mk-300", "tank-g", "valeton-gp200"] }),
  item({ id: "annblack-box", name: "ANNBLACK BOX", category: "multiefeitos", instruments: ["guitarra", "baixo", "violao"], ir: true, software: "M-EFCS / ANNlab", summary: "Modelador portátil com cadeia de efeitos, simulação de amplificador e gabinete e suporte a recursos ANN.", bestFor: "Músico que quer timbres de guitarra e baixo em uma caixa pequena e editável.", avoidIf: "Você não quer depender de aplicativo para organizar recursos e presets.", pros: ["Guitarra e baixo", "Cadeia editável", "Formato pequeno"], cons: ["Ecossistema ANN exige aprendizado", "Poucos controles físicos"], specs: [["Perfil", "Guitarra e baixo"], ["IR", "CAB/IR do usuário"], ["Editor", "M-EFCS e ANNlab"], ["Formato", "Desktop compacto"]], amazonQuery: "M-VAVE ANNBLACK BOX pedaleira", featured: true, related: ["mk-300", "tank-pro", "ir-box"] }),
  item({ id: "mk-20", name: "MK-20", category: "multiefeitos", instruments: ["guitarra", "baixo"], ir: true, software: "M-EFCS", summary: "Processador multiefeitos com pedal de expressão e edição pelo ecossistema M-EFCS.", bestFor: "Quem quer pedal de expressão integrado e controles de chão mais convencionais.", avoidIf: "Você quer o menor equipamento possível.", pros: ["Expressão integrada", "Editor oficial", "Mais controle ao vivo"], cons: ["Ocupa mais espaço", "Firmware deve corresponder ao modelo exato"], specs: [["Perfil", "Guitarra e baixo"], ["Controle", "Pedal de expressão"], ["Editor", "M-EFCS"], ["Firmware", "Portal oficial"]], amazonQuery: "M-VAVE MK-20 pedaleira", related: ["mk-300", "tank-g", "zoom-g1x-four"] }),
  item({ id: "mk-300", name: "MK-300", category: "multiefeitos", instruments: ["guitarra", "baixo", "violao"], ir: true, software: "M-EFCS", summary: "Processador mais completo com centenas de efeitos, presets, looper e carregamento de IR pelo editor.", bestFor: "Quem toca mais de um instrumento ou quer um centro de rig com mais recursos.", avoidIf: "Você precisa de algo ultracompacto para levar no bolso.", pros: ["Biblioteca ampla", "Carrega IR", "Mais conexões e controles"], cons: ["Curva de aprendizado maior", "Exige organização de presets"], specs: [["Perfil", "Guitarra e baixo"], ["Efeitos", "300+ na linha atual"], ["Editor", "M-EFCS"], ["Uso", "Palco e estúdio"]], amazonQuery: "M-VAVE MK-300 pedaleira", featured: true, related: ["tank-pro", "annblack-box", "hotone-ampero-mini"] }),
  item({ id: "h8", name: "H8", category: "multiefeitos", instruments: ["guitarra"], ir: true, software: "CubeSuite", summary: "Processador compacto para guitarra com modelos de amplificador e efeitos, gerenciado pelo CubeSuite.", bestFor: "Quem quer uma alternativa compacta dentro do ecossistema CubeSuite.", avoidIf: "Você precisa de documentação extensa ou muitos controles dedicados.", pros: ["Compacto", "CubeSuite", "Seção de gabinete"], cons: ["Menos comum no mercado", "Confira disponibilidade de documentação"], specs: [["Perfil", "Guitarra"], ["Editor", "CubeSuite"], ["Conexão", "USB"], ["Categoria", "Multiefeitos"]], amazonQuery: "M-VAVE H8 pedaleira", related: ["cube-baby", "tank-mini", "ir-box"] }),
  item({ id: "pocket-amp", name: "POCKET AMP", category: "pratica", instruments: ["guitarra"], software: "M-EFCS", summary: "Simulador de amplificador de bolso com saída para fones, feito para prática silenciosa.", bestFor: "Estudar guitarra com fones e carregar o setup no bolso.", avoidIf: "Seu foco é controlar presets com os pés no palco.", pros: ["Muito portátil", "Saída de fones", "Editor oficial"], cons: ["Não substitui pedaleira de palco", "Poucos controles físicos"], specs: [["Uso", "Prática silenciosa"], ["Saída", "Fones"], ["Editor", "M-EFCS"], ["Formato", "Bolso"]], amazonQuery: "M-VAVE Pocket Amp guitarra", related: ["mini-x", "nux-mighty-plug-pro", "cube-baby"] }),
  item({ id: "mini-x", name: "MINI-X", category: "pratica", instruments: ["guitarra"], summary: "Amplificador de fones com nove timbres, streaming sem fio e bateria recarregável.", bestFor: "Prática rápida, playback e estudo sem montar pedalboard.", avoidIf: "Você precisa carregar IR próprio ou montar cadeias complexas.", pros: ["Nove timbres", "Streaming sem fio", "Bateria"], cons: ["Uso focado em estudo", "Sem footswitch"], specs: [["Uso", "Fones"], ["Timbres", "9 amps"], ["Bateria", "cerca de 5 h"], ["Áudio", "Streaming sem fio"]], amazonQuery: "M-VAVE MINI-X headphone amp", related: ["pocket-amp", "nux-mighty-plug-pro", "cube-baby"] }),
  item({ id: "ir-box", name: "IR BOX", category: "ir-loader", ir: true, software: "CubeSuite / MidiSuite", summary: "Carregador dedicado de IR com saída balanceada XLR para integrar preamps e pedais ao PA.", bestFor: "Quem já gosta dos próprios pedais e só precisa de gabinete/IR e saída direta.", avoidIf: "Você procura uma pedaleira com amps, drives e modulações completos.", pros: ["Função dedicada", "Saída XLR", "Carrega WAV"], cons: ["Precisa de preamp/amp sim antes", "Não substitui multiefeitos"], specs: [["Função", "IR loader"], ["Formato", "WAV 44,1 kHz / 24-bit / 2048"], ["Saída", "XLR balanceada"], ["Editor", "CubeSuite"]], amazonQuery: "M-VAVE IR BOX pedal impulse response", featured: true, related: ["boss-ir2", "cube-baby", "annblack-box"] }),
  item({ id: "looper-drum", name: "LOOPER DRUM", category: "pedais", instruments: ["guitarra", "baixo", "violao"], software: "CubeSuite", summary: "Looper com bateria eletrônica para estudo, composição e apresentações solo.", bestFor: "Praticar tempo, criar bases e tocar sozinho com acompanhamento.", avoidIf: "Você precisa de múltiplas trilhas independentes ou sincronismo profissional avançado.", pros: ["Looper e bateria", "Bom para estudo", "Editor CubeSuite"], cons: ["Fluxo exige prática", "Limites variam por revisão"], specs: [["Função", "Looper + bateria"], ["Editor", "CubeSuite"], ["Instrumentos", "Uso geral"], ["Uso", "Estudo e performance"]], amazonQuery: "M-VAVE Looper Drum pedal", related: ["looper-pro", "chocolate-plus", "cube-turner-plus"] }),
  item({ id: "looper-pro", name: "LOOPER PRO", category: "pedais", software: "CubeSuite", summary: "Looper de chão para construir camadas e controlar gravações com os pés.", bestFor: "Músicos que querem bases próprias sem levar computador.", avoidIf: "Você precisa de uma estação multitrilha completa.", pros: ["Controle de pé", "Editor oficial", "Uso com vários instrumentos"], cons: ["Requer domínio do tempo", "Confira a revisão do produto"], specs: [["Função", "Looper"], ["Editor", "CubeSuite"], ["Conexão", "USB"], ["Uso", "Palco e estudo"]], amazonQuery: "M-VAVE Looper Pro pedal", related: ["looper-drum", "chocolate", "cube-turner-plus"] }),
  item({ id: "mini-universe", name: "MINI-UNIVERSE", category: "pedais", instruments: ["guitarra"], summary: "Pedal compacto de reverb ambiente para texturas, ambiência e sons espaciais.", bestFor: "Ambient, worship e quem quer reverbs criativos em pouco espaço.", avoidIf: "Você procura um reverb básico com muitos presets salvos.", pros: ["Compacto", "Texturas ambientes", "Operação direta"], cons: ["Sem editor", "Recursos focados em ambiência"], specs: [["Efeito", "Reverb"], ["Perfil", "Ambient"], ["Formato", "Mini pedal"], ["Controle", "Painel físico"]], amazonQuery: "M-VAVE Mini Universe reverb", related: ["elemental", "galaxia", "mini-efx"] }),
  item({ id: "elemental", name: "ELEMENTAL", category: "pedais", instruments: ["guitarra"], summary: "Delay digital compacto para repetições, ambiência e bases rítmicas.", bestFor: "Adicionar delay a um setup simples sem ocupar muito espaço.", avoidIf: "Você precisa de presets, MIDI ou edição em software.", pros: ["Simples", "Compacto", "Bom custo de entrada"], cons: ["Sem presets", "Sem MIDI"], specs: [["Efeito", "Delay"], ["Formato", "Mini pedal"], ["Controle", "Painel físico"], ["Uso", "Pedalboard"]], amazonQuery: "M-VAVE Elemental delay", related: ["mini-universe", "galaxia", "classic-delay"] }),
  item({ id: "galaxia", name: "GALAXIA", category: "pedais", instruments: ["guitarra"], summary: "Reverb estéreo com nove algoritmos, incluindo shimmer, cloud, bloom, swell e lo-fi.", bestFor: "Quem quer reverbs modernos e estéreo para palco ou gravação.", avoidIf: "Você só precisa de um room simples e barato.", pros: ["Nove algoritmos", "Estéreo", "MASH/freeze"], cons: ["Mais controles para aprender", "Disponibilidade pode variar"] , specs: [["Efeito", "Reverb estéreo"], ["Algoritmos", "9"], ["Recurso", "MASH freeze"], ["Uso", "Palco e estúdio"]], amazonQuery: "M-VAVE Galaxia reverb", related: ["mini-universe", "elemental-pro", "mini-efx"] }),
  item({ id: "elemental-pro", name: "ELEMENTAL PRO", category: "pedais", instruments: ["guitarra"], summary: "Delay estéreo de modelagem com nove tipos, tap tempo, ping-pong e hold infinito.", bestFor: "Pedalboards estéreo e músicos que usam delay como parte da performance.", avoidIf: "Você quer apenas um eco simples com três controles.", pros: ["Estéreo", "Tap tempo", "Nove tipos"], cons: ["Mais complexo que um delay básico", "Modelo recente"] , specs: [["Efeito", "Delay estéreo"], ["Tipos", "9"], ["Recursos", "Tap, hold e ping-pong"], ["Controle", "MASH"]], amazonQuery: "M-VAVE Elemental Pro delay", related: ["elemental", "galaxia", "mini-universe"] }),

  item({ id: "chocolate", name: "Chocolate", category: "midi", instruments: [], software: "CubeSuite / SincoOTA", summary: "Controlador MIDI de pé compacto com quatro footswitches; também funciona como virador de páginas sem fio.", bestFor: "Controlar apps, plugins, tablets, playback e páginas sem usar as mãos.", avoidIf: "Você precisa de muitos switches, displays grandes ou MIDI DIN sem adaptadores.", pros: ["Quatro footswitches", "Bluetooth e USB", "Até 12 h de uso"], cons: ["Programação inicial exige app", "Funções variam conforme o aplicativo"], specs: [["Tipo", "Controlador MIDI de pé"], ["Footswitches", "4"], ["Conexão", "Bluetooth / USB"], ["Bateria", "até 12 h"]], officialUrl: "https://www.m-vave.com/product?id=chocolate", amazonQuery: "M-VAVE Chocolate controlador MIDI", featured: true, related: ["chocolate-plus", "cube-turner-pro", "midi-system"] }),
  item({ id: "chocolate-plus", name: "CHOCOLATE PLUS", category: "midi", instruments: [], software: "CubeSuite / SincoOTA", summary: "Evolução do Chocolate para controle MIDI e virada de páginas com mais possibilidades de comando.", bestFor: "Quem quer um controlador de pé pequeno para palco, estudo e tablet.", avoidIf: "Você precisa de um controlador grande com vários bancos visíveis ao mesmo tempo.", pros: ["Compacto", "Controle sem fio", "Uso musical e page turner"], cons: ["Exige configuração por app", "Confirme compatibilidade com seu app"], specs: [["Tipo", "Controlador/page turner"], ["Conexão", "Sem fio e USB"], ["Editor", "CubeSuite"], ["Uso", "Mãos livres"]], amazonQuery: "M-VAVE Chocolate Plus controlador MIDI", featured: true, related: ["chocolate", "cube-turner-plus", "midi-system"] }),
  item({ id: "cube-turner-pro", name: "CUBE TURNER PRO", category: "page-turner", instruments: [], software: "CubeSuite / SincoOTA", summary: "Virador de páginas sem fio profissional para partituras, letras, apresentações e leitura em tablets.", bestFor: "Músicos, professores e leitores que precisam avançar páginas com os pés.", avoidIf: "Seu aplicativo não aceita comandos de teclado ou page turner configurável.", pros: ["Operação mãos livres", "Formato de chão", "Configuração por app"], cons: ["Compatibilidade depende do aplicativo", "Não é uma pedaleira de efeitos"], specs: [["Tipo", "Virador de páginas"], ["Controle", "Pelos pés"], ["Conexão", "Sem fio"], ["Uso", "Tablet e computador"]], amazonQuery: "M-VAVE Cube Turner Pro page turner", featured: true, related: ["cube-turner-plus", "chocolate", "chocolate-plus"] }),
  item({ id: "cube-turner-plus", name: "CUBE TURNER PLUS", category: "page-turner", instruments: [], software: "CubeSuite / SincoOTA", summary: "Virador de páginas sem fio com recursos expandidos e integração a fluxos de looper compatíveis.", bestFor: "Quem usa partituras digitais e quer comandos extras em um único pedal.", avoidIf: "Você quer apenas um botão simples e não usará os modos adicionais.", pros: ["Recursos ampliados", "Mãos livres", "Integração com apps"], cons: ["Configuração pode variar por modo", "Confira o app antes da compra"], specs: [["Tipo", "Virador de páginas"], ["Conexão", "Sem fio"], ["Editor", "CubeSuite"], ["Extra", "Integração com looper"]], amazonQuery: "M-VAVE Cube Turner Plus", featured: true, related: ["cube-turner-pro", "chocolate-plus", "looper-drum"] }),
  item({ id: "smk25", name: "SMK25", category: "midi", instruments: [], software: "MidiSuite / CubeSuite", summary: "Teclado controlador MIDI portátil de 25 teclas para produção, estudo e performance.", bestFor: "Home studio compacto e uso com computador, celular ou tablet.", avoidIf: "Você precisa de tessitura ampla para tocar com as duas mãos.", pros: ["Portátil", "Ecossistema MidiSuite", "Uso móvel"], cons: ["25 teclas limitam a extensão", "Não gera som sozinho"], specs: [["Tipo", "Teclado MIDI"], ["Teclas", "25"], ["Editor", "MidiSuite"], ["Uso", "DAW e apps"]], amazonQuery: "M-VAVE SMK25 controlador MIDI", featured: true, related: ["smk25-ii", "smk25-mini", "arturia-minilab3"] }),
  item({ id: "smk25-ii", name: "SMK25-II", category: "midi", instruments: [], software: "MidiSuite / SincoOTA", summary: "Segunda geração do controlador de 25 teclas com configuração pelo MidiSuite.", bestFor: "Produção portátil com pads, controles e integração a DAWs.", avoidIf: "Você precisa de teclas em tamanho completo ou mais oitavas simultâneas.", pros: ["Segunda geração", "Portátil", "Editor dedicado"], cons: ["Poucas oitavas", "Mapeamento depende da DAW"], specs: [["Tipo", "Teclado MIDI"], ["Teclas", "25"], ["Editor", "MidiSuite"], ["Firmware", "SincoOTA"]], amazonQuery: "M-VAVE SMK25 II controlador MIDI", related: ["smk25", "smk37-pro", "akai-mpk-mini"] }),
  item({ id: "smk25-mini", name: "SMK25 Mini", category: "midi", instruments: [], software: "MidiSuite / SincoOTA", summary: "Controlador MIDI ainda menor, pensado para mochila, mesa pequena e criação móvel.", bestFor: "Beatmaker ou músico que prioriza espaço e mobilidade.", avoidIf: "Sua técnica exige teclas maiores e mais extensão.", pros: ["Muito compacto", "Editor MidiSuite", "Bom para viagem"], cons: ["Teclas e alcance reduzidos", "Não é instrumento autônomo"], specs: [["Tipo", "Teclado MIDI mini"], ["Teclas", "25"], ["Editor", "MidiSuite"], ["Uso", "Produção móvel"]], amazonQuery: "M-VAVE SMK25 Mini MIDI", related: ["smk25-ii", "akai-mpk-mini", "arturia-minilab3"] }),
  item({ id: "smk37-pro", name: "SMK-37 PRO", category: "midi", instruments: [], software: "MidiSuite", summary: "Controlador MIDI de 37 teclas para quem precisa de mais extensão sem perder portabilidade.", bestFor: "Arranjos, acordes e performance com mais alcance que um modelo de 25 teclas.", avoidIf: "Sua mesa ou mochila só comporta um controlador mini.", pros: ["37 teclas", "Mais extensão", "MidiSuite"], cons: ["Maior que a linha SMK25", "Não possui sons internos"], specs: [["Tipo", "Teclado MIDI"], ["Teclas", "37"], ["Editor", "MidiSuite"], ["Uso", "DAW e performance"]], amazonQuery: "M-VAVE SMK 37 Pro MIDI", related: ["smk37-elite", "smk25-ii", "arturia-minilab3"] }),
  item({ id: "smk37-elite", name: "SMK-37 ELITE", category: "midi", instruments: [], software: "MidiSuite", summary: "Controlador de 37 teclas da linha Elite para produção e performance com maior área de controle.", bestFor: "Quem quer mais controles e alcance em um controlador ainda transportável.", avoidIf: "Preço e tamanho mínimos são prioridade.", pros: ["37 teclas", "Linha avançada", "Editor MidiSuite"], cons: ["Ocupa mais mesa", "Mapeamento exige preparação"], specs: [["Tipo", "Teclado MIDI"], ["Teclas", "37"], ["Linha", "Elite"], ["Editor", "MidiSuite"]], amazonQuery: "M-VAVE SMK 37 Elite MIDI", related: ["smk37-pro", "smk25-ii", "akai-mpk-mini"] }),
  item({ id: "smc-pad", name: "SMC-PAD", category: "midi", instruments: [], software: "MidiSuite / SincoOTA", summary: "Controlador MIDI de pads para bateria, samples, clips e comandos de DAW.", bestFor: "Beatmaking e disparo de samples sem depender do teclado do computador.", avoidIf: "Você procura teclas melódicas ou sons internos.", pros: ["Pads dedicados", "Mapeável", "Editor MidiSuite"], cons: ["Depende de software", "Mapeamento varia por DAW"], specs: [["Tipo", "Controlador de pads"], ["Uso", "Drums e samples"], ["Editor", "MidiSuite"], ["Firmware", "SincoOTA"]], amazonQuery: "M-VAVE SMC PAD controlador MIDI", related: ["smc-pad-pocket", "smc-mixer", "smk25"] }),
  item({ id: "smc-pad-pocket", name: "SMC-PAD Pocket", category: "midi", instruments: [], software: "MidiSuite", summary: "Versão compacta do controlador de pads para produção móvel e mesas pequenas.", bestFor: "Criar beats e disparar samples com o mínimo de espaço.", avoidIf: "Você precisa de muitos pads e controles simultâneos.", pros: ["Cabe na mochila", "Pads físicos", "MidiSuite"], cons: ["Área de controle reduzida", "Requer app ou DAW"], specs: [["Tipo", "Pads MIDI compactos"], ["Uso", "Produção móvel"], ["Editor", "MidiSuite"], ["Conexão", "USB/MIDI"]], amazonQuery: "M-VAVE SMC PAD Pocket", related: ["smc-pad", "smk25-mini", "akai-mpk-mini"] }),
  item({ id: "smc-mixer", name: "SMC-Mixer", category: "midi", instruments: [], software: "MidiSuite / SincoOTA", summary: "Superfície de controle MIDI para volumes, parâmetros e automação dentro da DAW.", bestFor: "Quem quer tirar o mixer da tela e controlar faixas com movimentos físicos.", avoidIf: "Você está procurando uma interface de áudio com entradas de microfone.", pros: ["Controle tátil", "Mapeável", "Editor MidiSuite"], cons: ["Não é mixer de áudio", "Configuração depende da DAW"], specs: [["Tipo", "Superfície MIDI"], ["Uso", "Mixagem e automação"], ["Editor", "MidiSuite"], ["Firmware", "SincoOTA"]], amazonQuery: "M-VAVE SMC Mixer MIDI", related: ["smc-pad", "smk25", "midi-system"] }),
  item({ id: "midi-system", name: "MIDI SYSTEM", category: "acessorios", instruments: [], software: "CubeSuite / SincoOTA", summary: "Sistema para transmitir MIDI sem fio e reduzir cabos entre controladores e instrumentos compatíveis.", bestFor: "Palco, teclado e pedalboard que já usam MIDI e precisam de ligação sem cabo.", avoidIf: "Seus aparelhos não oferecem as conexões MIDI exigidas pelo kit.", pros: ["Menos cabos", "Uso com vários setups", "Configuração por app"], cons: ["Não cria comandos sozinho", "Compatibilidade precisa ser conferida"], specs: [["Função", "Transmissão MIDI sem fio"], ["Editor", "CubeSuite"], ["Firmware", "SincoOTA"], ["Uso", "Palco e estúdio"]], amazonQuery: "M-VAVE MIDI System wireless", related: ["chocolate", "chocolate-plus", "smk25"] }),

  item({ id: "nux-mighty-plug-pro", brand: "NUX", name: "Mighty Plug Pro", category: "pratica", instruments: ["guitarra", "baixo"], ir: true, software: "MightyAmp / firmware oficial", officialUrl: "https://nuxaudio.com/product/mightyplugpro/", summary: "Amplificador de fones com efeitos, aplicativo, USB-C para gravação e atualizações oficiais.", bestFor: "Estudo silencioso e gravação móvel com um ecossistema de app mais maduro.", avoidIf: "Você precisa acionar presets com os pés no palco.", pros: ["Guitarra e baixo", "USB-C de áudio", "App e firmware"], cons: ["Formato de prática", "Sem footswitch"], specs: [["Tipo", "Headphone amp"], ["Instrumentos", "Guitarra e baixo"], ["USB", "Áudio e firmware"], ["Uso", "Estudo e gravação"]], amazonQuery: "NUX Mighty Plug Pro", featured: true, related: ["pocket-amp", "mini-x", "cube-baby"] }),
  item({ id: "zoom-g1x-four", brand: "ZOOM", name: "G1X FOUR", category: "multiefeitos", instruments: ["guitarra"], ir: false, software: "Guitar Lab", officialUrl: "https://zoomcorp.com/en/us/multi-effects/guitar-effects/g1-four-g1x-four/g1g1x-four/", summary: "Multiefeitos de entrada com mais de 70 efeitos/modelos, looper, bateria e pedal de expressão.", bestFor: "Iniciante que quer muitos efeitos, ritmos e expressão em um pedal tradicional.", avoidIf: "Carregar IR próprio é requisito obrigatório.", pros: ["Pedal de expressão", "Looper e bateria", "Guitar Lab"], cons: ["Não é IR loader", "Interface de geração anterior"], specs: [["Efeitos e amps", "70+"], ["Ritmos", "68"], ["Controle", "Expressão"], ["Editor", "Guitar Lab"]], amazonQuery: "Zoom G1X Four pedaleira", related: ["tank-g", "mk-20", "hotone-ampero-mini"] }),
  item({ id: "hotone-ampero-mini", brand: "Hotone", name: "Ampero Mini", category: "multiefeitos", instruments: ["guitarra", "baixo", "violao"], ir: true, software: "Ampero Editor", officialUrl: "https://shop.hotoneaudio.com/products/ampero-mini", summary: "Modelador compacto com tela touch, cadeia editável, nove módulos simultâneos e IR de terceiros.", bestFor: "Quem quer uma interface mais visual, bons recursos de estúdio e tamanho compacto.", avoidIf: "Você precisa de muitos footswitches integrados.", pros: ["Tela touch", "IR de terceiros", "USB de áudio"], cons: ["Poucos footswitches", "Fonte externa"], specs: [["Módulos", "até 9"], ["Presets", "198"], ["Looper", "até 100 s"], ["IR", "Loader do usuário"]], amazonQuery: "Hotone Ampero Mini", featured: true, related: ["mk-300", "tank-pro", "sonicake-matribox-ii"] }),
  item({ id: "sonicake-matribox-ii", brand: "Sonicake", name: "Matribox II", category: "multiefeitos", instruments: ["guitarra", "baixo"], ir: true, software: "Editor Sonicake", officialUrl: "https://www.sonicake.com/products/matribox-ii", summary: "Segunda geração da pedaleira Matribox, com modelagem, efeitos e fluxo moderno de presets.", bestFor: "Quem busca uma alternativa de preço intermediário às pedaleiras M-VAVE.", avoidIf: "Você quer o ecossistema de suporte mais consolidado possível.", pros: ["Geração atual", "Formato de chão", "Boa variedade"], cons: ["Disponibilidade varia no Brasil", "Confira o suporte a IR na revisão anunciada"], specs: [["Tipo", "Multiefeitos"], ["Geração", "Matribox II"], ["Editor", "Sonicake"], ["Uso", "Palco e estudo"]], amazonQuery: "Sonicake Matribox II pedaleira", related: ["hotone-ampero-mini", "tank-pro", "valeton-gp200"] }),
  item({ id: "valeton-gp200", brand: "Valeton", name: "GP-200", category: "multiefeitos", instruments: ["guitarra", "baixo", "violao"], ir: true, software: "GP-200 Editor", officialUrl: "https://www.valeton.net/product/gp-200/", summary: "Pedaleira completa com tela, múltiplos footswitches, expressão e suporte a IR para palco e estúdio.", bestFor: "Quem precisa de controle físico e conexões sem subir para a faixa premium.", avoidIf: "Tamanho e simplicidade são mais importantes que recursos.", pros: ["Muitos controles", "Expressão integrada", "Carrega IR"], cons: ["Maior e mais pesada", "Mais menus para aprender"], specs: [["Tipo", "Multiefeitos"], ["Controle", "Footswitches + expressão"], ["IR", "Loader do usuário"], ["Uso", "Palco e estúdio"]], amazonQuery: "Valeton GP-200 pedaleira", related: ["tank-pro", "hotone-ampero-mini", "line6-hx-stomp"] }),
  item({ id: "line6-hx-stomp", brand: "Line 6", name: "HX Stomp", category: "multiefeitos", instruments: ["guitarra", "baixo", "violao"], ir: true, software: "HX Edit", officialUrl: "https://line6.com/hx-stomp/", summary: "Processador compacto da família Helix com amps, efeitos, roteamento, MIDI, interface de áudio e IR loader.", bestFor: "Setup profissional compacto, integração com outros pedais e gravação.", avoidIf: "Seu orçamento é de entrada ou você quer operação extremamente simples.", pros: ["Ecossistema Helix", "Roteamento flexível", "IR e áudio USB"], cons: ["Investimento alto", "Só três footswitches integrados"], specs: [["Família", "Helix/HX"], ["IR", "Loader integrado"], ["Editor", "HX Edit"], ["Uso", "Profissional compacto"]], amazonQuery: "Line 6 HX Stomp", featured: true, related: ["boss-ir2", "valeton-gp200", "hotone-ampero-mini"] }),
  item({ id: "boss-ir2", brand: "BOSS", name: "IR-2", category: "ir-loader", instruments: ["guitarra"], ir: true, software: "IR-2 IR Loader", officialUrl: "https://www.boss.info/br/products/ir-2/", summary: "Amp e cabinet em formato de pedal compacto, com 11 tipos, IRs Celestion, loop estéreo, fones e USB-C.", bestFor: "Pedalboard tradicional que precisa ir direto ao PA com operação simples.", avoidIf: "Você quer modulações, delays e reverbs completos dentro do mesmo aparelho.", pros: ["Operação direta", "11 slots/tipos", "USB-C e loop estéreo"], cons: ["Focado em amp/cab", "Poucos presets ao vivo"], specs: [["Amps", "11 tipos"], ["User IR", "11 posições compartilhadas"], ["Áudio", "96 kHz / 32-bit float interno"], ["Editor", "IR-2 IR Loader"]], amazonQuery: "BOSS IR-2 Amp Cabinet", featured: true, related: ["ir-box", "line6-hx-stomp", "hotone-ampero-mini"] }),
  item({ id: "akai-mpk-mini", brand: "Akai Professional", name: "MPK mini mk3", category: "midi", instruments: [], ir: false, software: "MPC Beats / editor Akai", officialUrl: "https://www.akaipro.com/mpk-mini-mk3", summary: "Controlador popular de 25 teclas com pads MPC, knobs e amplo suporte em DAWs.", bestFor: "Primeiro controlador para beats, home studio e produção musical.", avoidIf: "Você precisa de teclas maiores ou controle de pé.", pros: ["Ecossistema consolidado", "Pads MPC", "Muitos tutoriais"], cons: ["25 teclas", "Sem Bluetooth nativo"], specs: [["Tipo", "Teclado MIDI"], ["Teclas", "25"], ["Pads", "8 MPC"], ["Uso", "Produção musical"]], amazonQuery: "Akai MPK Mini MK3", related: ["smk25-ii", "smk25-mini", "arturia-minilab3"] }),
  item({ id: "arturia-minilab3", brand: "Arturia", name: "MiniLab 3", category: "midi", instruments: [], ir: false, software: "Arturia Software Center", officialUrl: "https://www.arturia.com/products/hybrid-synths/minilab-3/overview", summary: "Controlador de 25 teclas com pads, encoders, faders e integração a software de produção.", bestFor: "Home studio que valoriza pacote de software e integração pronta com DAWs.", avoidIf: "Você quer controle sem fio ou mais de duas oitavas.", pros: ["Bom pacote de software", "Faders e encoders", "Integração com DAW"], cons: ["25 teclas", "USB com fio"], specs: [["Tipo", "Teclado MIDI"], ["Teclas", "25"], ["Controles", "Pads, knobs e faders"], ["Uso", "Home studio"]], amazonQuery: "Arturia MiniLab 3", related: ["smk25", "akai-mpk-mini", "smk37-pro"] })
];

export const SOFTWARE_MATRIX = [
  { name: "CubeSuite", platforms: "Windows, macOS, iOS e Android", products: "Cube Baby, Cube Baby AC/Bass, H8, IR Box, loopers, Chocolate e Cube Turner", use: "Editar, transferir IRs, configurar controles e gerenciar funções compatíveis.", url: MVAVE_DOWNLOADS },
  { name: "M-EFCS", platforms: "Windows, macOS, iOS e Android", products: "TANK-G/B, ANNBLACK BOX, TANK MINI, POCKET AMP, SP100, MK-300 e MK-20", use: "Editar presets, amps, efeitos e recursos do processador.", url: MVAVE_DOWNLOADS },
  { name: "MidiSuite", platforms: "Windows, macOS, iOS e Android", products: "SMK25, SMK25-II/Mini, SMK-37, SMC-PAD, SMC-Mixer e outros controladores", use: "Mapear MIDI, curvas, pads, knobs, faders e comportamento de controles.", url: MVAVE_DOWNLOADS },
  { name: "M-UPGRADE", platforms: "Windows e macOS", products: "Modelos com pacote de firmware compatível", use: "Gravar firmware no equipamento. Use somente o arquivo do modelo e revisão exatos.", url: MVAVE_DOWNLOADS },
  { name: "SincoOTA", platforms: "iOS e Android", products: "Chocolate, Cube Turner, SMK/SMC, loopers, MIDI System e IR Box", use: "Atualizar firmware móvel dos produtos listados oficialmente.", url: MVAVE_DOWNLOADS },
  { name: "ANNlab", platforms: "Computador", products: "Linha ANN", use: "Treinamento e gerenciamento de recursos ANN compatíveis.", url: MVAVE_DOWNLOADS }
];

// Acessíveis somente por URL direta. Não aparecem em menus, homepage ou sitemap.
export const TONE_RECIPES_ENABLED = true;
export const TONE_RECIPES_LISTED = false;
export const STORE_ENABLED = true;
export const STORE_LISTED = false;

export const TONE_RECIPES = [
  { id: "clean-americano", name: "Clean americano aberto", instrument: "guitarra", equipment: ["cube-baby", "tank-g", "mk-300"], irFamily: "Fender / open back", audioBefore: null, audioAfter: null, order: ["Amp clean com ganho baixo", "IR open back", "Low cut suave", "Reverb curto"], note: "Gravar acordes abertos e fraseado, sem mudar a execução entre antes/depois." },
  { id: "crunch-britanico", name: "Crunch britânico definido", instrument: "guitarra", equipment: ["tank-g", "annblack-box", "line6-hx-stomp"], irFamily: "Marshall 4x12", audioBefore: null, audioAfter: null, order: ["Amp britânico em crunch", "IR 4x12", "Corte de graves", "Delay opcional"], note: "Gravar palhetada leve e forte para mostrar dinâmica." },
  { id: "baixo-mix", name: "Baixo presente na mix", instrument: "baixo", equipment: ["cube-baby-bass", "tank-b", "mk-300"], irFamily: "Ampeg / 8x10", audioBefore: null, audioAfter: null, order: ["Compressor leve", "Preamp", "IR de baixo", "Ajuste de nível"], note: "Gravar solo e junto de bateria para revelar o encaixe." },
  { id: "violao-natural", name: "Violão em linha mais natural", instrument: "violao", equipment: ["cube-baby-ac", "ir-box", "annblack-box"], irFamily: "Taylor / Martin", audioBefore: null, audioAfter: null, order: ["Entrada sem clip", "IR de violão", "EQ corretiva mínima", "Ambiência curta"], note: "Gravar dedilhado e batida com o mesmo ganho." }
];

export function equipmentById(id) {
  return EQUIPMENT_ITEMS.find(function(product) { return product.id === id; });
}

export function amazonSearchUrl(query) {
  return "https://www.amazon.com.br/s?k=" + encodeURIComponent(query) + "&s=price-asc-rank";
}
